---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  become: yes

- name: Install npm
  apt:
    name: npm
    state: present
  become: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present