---
- name: Install npm
  apt:
    name: npm
    state: present
  become: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create folder
  become: true
  file:
    path: /home/app
    state: directory
    mode: 0755

- name: Copy tarball to remote host
  become: true
  copy:
    src: "~/project/artifact.tar.gz"
    dest: /home/app
#    mode: '0644'

- name: Extract artifact
  become: true
  shell: |
    cd /home/app
    tar -xvzf artifact.tar.gz

- name: Install and start application
  become: true
  shell: |
    ls -l
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
