---
- name: Install npm
  apt:
    name: npm
    state: present
  become: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy tarball to remote host
  copy:
    src: "{{ tarball_name }}"
    dest: "{{ tarball_name }}"
    mode: '0644'

# - name: Ensure destination directory exists
#   file:
#     path: "{{ dest_dir }}"
#     state: directory
#     mode: '0755'
- name: Extract tarball
  unarchive:
    src: "{{ tarball_name }}"
    dest: "{{ dest_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Install and start application
  shell: |
    ls -l
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
